name: checkmate

services:
  backend:
    container_name: backend
    image: eliashahn12/checkmate-backend:latest
    networks: 
      - main

  frontend:
    container_name: frontend
    image: eliashahn12/checkmate-frontend:latest
    networks: 
      - main

networks:
  main:
    external: true